language: python
python:
- '3.6'
env:
- DJANGO_VERSION=1.11.4
install:
- pip install -r requirements.txt
before_script:
- python3 manage.py makemigrations
- python3 manage.py migrate
script:
- python3 manage.py test
deploy:
  provider: heroku
  api_key:
    secure: rr7g7CYd7x+4MuK5DvZTEKtop/foW634H0DbK7Md7Szwm7SB3uY0r/8SnZRl5IBdqswokhFLA/xiLMY4srVRjI8x+MBB9SVVrqpKsSbX+H1EQn4yoeCf9zCK+kCFJ0xYCMw2nuCiHT7hwuTYu4pBypXdECAbi10S3+OI+s03gVaBMrKmpJ80jfBpJbcRBWkfO8kanTDHt+qI4biyO023NG1X98vVaoj27jk2AvW8wMpMkE5tKLb1yupSiXxFqqavLpwPmN0WhOGO6rzq4UQ4KfQI1mGfJFGHSHC5AQEjk6IuDil5hB84008sywMAG7D3WchyYiHGaBx7PCCfqLC8CWNty8m0G/8c8JsaGWIHtqn91kBiYrzS7v9xbKmxRerAb3PRDH4np7bLMcNGj+qSz6MAJUMawWhe0BORHbm9ahhLD5mwkN4IHdCOm4T+sN9yFeSC/EL56E0Rmz5wflFWRvY31EWCvnm3PRiPGxg9WaOYN13kLrlUPyDALVLlGHggbCjMsxDx22+IWrtjrR0H+MKtMD5TPwpmhZoYBhe9rBKKuLp/irm/mwwu2xdiru2eX6F8RJWMCy513HUHgkzRSxaEggRrzryg+sjFsQDJouJlYDwMnVHGoC6W3IHQwepTCBXxRABEEDZEkWX3lvDcbP9or+L5PClNainaaklnyOQ=
  app: gcs01-leticiadesouza-travis
